openapi: 3.0.0
info:
  version: 1.0.0
  title: ETD Local Admin
  description: This is the API Spec for ETD Local Admin. We use this api to manage the connection between Local Web UI and Geth client
servers:
  - url: "https://petstore.swagger.io/v1"
paths:
  /coinbase:
    description: Set or Get Coinbase for current device
    get:
      description: Get current coinbase
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  coinbase:
                    type: string
                    example: "0x221770bCF48cDc134a673345088eB762213B71Dc"
    post:
      description: Set user coinbase
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                coinbase:
                  type: string
                  example: "0x221770bCF48cDc134a673345088eB762213B71Dc"
      responses:
        201:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  coinbase:
                    type: string
                    example: "0x221770bCF48cDc134a673345088eB762213B71Dc"
                  time:
                    type: string
                    example: "2021-07-09T02:27:11+08:00"
                    description: Format in Moment JS

        500:
          description: "Cannot Set Etherbase"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Your coinbase is not in correct format"
                  time:
                    type: string
                    example: "2021-07-09T02:27:11+08:00"
                    description: Format in Moment JS
  /miner/start:
    description: Start Mining
    post:
      description: Start mining process
      responses:
        201:
          description: Success response
        500:
          description: "Cannot Start mining"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "You didn't set your coinbase"
                  time:
                    type: string
                    example: "2021-07-09T02:27:11+08:00"
                    description: Format in Moment JS
  /miner/stop:
    description: Stop Mining
    post:
      description: Stop mining process
      responses:
        201:
          description: Success response
        500:
          description: "Cannot Stop mining"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "You didn't set your coinbase"
                  time:
                    type: string
                    example: "2021-07-09T02:27:11+08:00"
                    description: Format in Moment JS
  /balance:
    description: Get the balance for the current device
    get:
      summary: Get the balance
      description: Get the current coinbase's balance
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  time:
                    type: string
                    example: "2021-07-09T02:27:11+08:00"
                    description: Format in Moment JS

                  balance:
                    type: number
                    example: 60
                    description: Balance

                  unit:
                    type: string
                    example: etd
                    description: Unit for the balance
  /status/geth:
    description: Get status of the current geth server.
    get:
      description: This will include all the info from geth clients.
        For example, peerCount, isMining, blockNumber,
        hash rate , local address, Geth Version, and latest block id.

      summary: Get Geth info
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    infoName:
                      type: string
                      description: Name of the info
                      example: Peer Count
                    infoValue:
                      type: string
                      description: Value of the info
                      example: "10"
        500:
          description: Unable to fetch geth info
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: We cannot connect to the Geth client. Make sure you start your Geth correctly.
                  time:
                    type: string
                    example: "2021-07-09T02:27:11+08:00"
                    description: Format in Moment JS

  /status/system:
    description: Get system status
    get:
      summary: Get system info
      description: Get system info.
        Including CPU usage, memory usage, hard drive usage,
        system time, docker image version, docker container status,
        and auto-update script status.
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    infoName:
                      type: string
                      description: Name of the info
                      example: CPU Usage
                    infoValue:
                      type: string
                      description: Value of the info
                      example: "10%"
  /logs:
    description: Get system logs
    get:
      summary: Get system logs
      description: Get system logs. For example, auto-update log, runner log, and docker logs.
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    logName:
                      type: string
                      description: Log File Name
                      example: Auto update.log
                    logValue:
                      type: string
                      description: Log File Content
                      example: "[2021-01-01] Check update"
  /peers/add:
    description: Add peer
    post:
      summary: Add peer
      description: Add new peer by providing peer url
      responses:
        201:
          description: Success response
        500:
          description: "Cannot Set Etherbase"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Your coinbase is not in correct format"
                  time:
                    type: string
                    example: "2021-07-09T02:27:11+08:00"
                    description: Format in Moment JS

  /peers:
    description: Peers' info
    get:
      summary: Get connected peers' info
      description: Will return all the connected peers
      responses:
        201:
          description: Success response
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    caps:
                      type: array
                      items:
                        type: string
                        example: "etd/61"
                    id:
                      type: string
                      example: "3f8f61999252251808972871bc810505d5b33f7de761c98810584279dce9ecabb0b7da0836978e6074f48e2b787048739c9dc1f734403c8adafc0716d16f4dcd"
                    name:
                      type: string
                      description: Geth client version
                      example: Geth/v1.3.5-34b622a2/linux/go1.6
                    network:
                      type: object
                      description: Network infomation for the connnected client
                      properties:
                        localAddress:
                          type: string
                          example: 192.168.0.105:49356
                        remoteAddress:
                          type: string
                          example: 73.217.192.86:30303
                    protocols:
                      type: object
                      properties:
                        etd:
                          type: object
                          properties:
                            difficulty:
                              type: number
                              description: Hash difficulty
                              example: 10197633442299193000
                            head:
                              type: string
                              example: "8f2c1a08cfc80eff8e2aa601254d6f094e0e801b2e4f0bf2aefffaead93daa41"
                            version:
                              type: number
                              example: 63
